using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using UnityEngine;

/// <summary>
/// Stores a resource produced by an <see cref="AutoFarm"><c>AutoFarm</c></see> and relates
/// it to how much of it that <c>AutoFarm</c> produces at one time.
/// </summary>
[Serializable]
public class ResourceData
{
    /// <summary>
    /// The resource held in this object.
    /// </summary>
    public ResourceList Resource { get => _resource; }
    [SerializeField] private ResourceList _resource = ResourceList.DIRT;

    /// <summary>
    /// The amount of this resource gained whenever a farm produces resources.
    /// </summary>
    public int AmountPer
    {
        get { return _amountPer; }
        set { _amountPer = (value < 0) ? 0 : value; }
    }
    [SerializeField] private int _amountPer = 1;

    /// <summary>
    /// Constructs a <c>ResourceData</c> instance that associates some resource with
    /// the amount generated by an <see cref="AutoFarm"/> at one time.
    /// </summary>
    /// <param name="resource">The resource type stored in this <c>ResourceData</c></param>
    /// <param name="amountPer">The amount of this resource generated at once</param>
    public ResourceData(ResourceList resource, int amountPer)
    {
        _resource = resource;
        _amountPer = amountPer;
    }

    /// <summary>
    /// Constructs a <c>ResourceData</c> instance that stores a resource to be generated by an <see cref="AutoFarm"/>
    /// </summary>
    /// <param name="resource">The resource type stored in this <c>ResourceData</c></param>
    public ResourceData(ResourceList resource) : this(resource, 1) { }
}

/// <summary>
/// Contains a list of <see cref="ResourceData"><c>ResourceData</c></see> objects that an
/// <see cref="AutoFarm"><c>AutoFarm</c></see> will gain upon leveling up.
/// </summary>
[Serializable]
public class PerLevelResources
{
    /// <summary>
    /// A list of resources that will be gained by a farm upon reaching a certain level.
    /// </summary>
    public ReadOnlyCollection<ResourceData> Resources { get => _resources.AsReadOnly(); }
    [SerializeField] private List<ResourceData> _resources = new();

    public PerLevelResources(List<ResourceData> resources)
    {
        _resources = resources;
    }
}